title: 
author: Madman2000
email: andrewdavistn2000@gmail.com
linkedin_username: www.linkedin.com/in/michael-davis-3906a3202
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my page! I am currently learning and strating to use Github and other various
  tools and languages! Really excited to continue my journey into the world of IT! If you want to talk
  to me, contact me at my email and I will get back as soon as I can!

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Madman2000 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
